### PR TITLE
Group participation fix

### LINKED ISSUE #429: Echidna wrongfully requires membership of all groups in joint publication
As illustrated in [this attempt to publish a Media Capture Task Force document](https://lists.w3.org/Archives/Public/public-tr-notifications/2017Apr/0013.html) (a joint task force between DAS and WebRTC), echdina currently requires membership of both groups in joint publications, whereas I can't think of any good reason to impose this.

### PR DESCRIPTION
**Pull request by deniak**
Echidna should check that the requester is participating in *at least* one WG delivering the spec.
Fix #429 
cc @dontcallmedom

### CODE REVIEW

File: lib/user-checker.js [hunk 1]
```diff
@@ -16,17 +16,18 @@ var UserChecker = {};
...
+    var delivererSet = new Set(delivererIDs);
 
-    for (var i = 0; i < delivererIDs.length; i++) {
-      if (groups.indexOf(delivererIDs[i]) < 0) {
-        errors = errors.push('You are not participating in group: ' +
-          delivererIDs[i]);
-      }
+    var participation = [...groups].filter(x => delivererSet.has(x));
+
+    if (participation.length === 0) {
```
Comment (tripu) [inline lib/user-checker.js]: These two lines and the variable could be replaced by this one:

```javascript
if ([...groups].some(x => delivererSet.has(x))) {
```

Comment (deniak) [inline lib/user-checker.js]: Thanks for the suggestion. I updated the PR.
